<?php

namespace AppBundle\Repository;

/**
 * DayTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayTaskRepository extends \Doctrine\ORM\EntityRepository
{
	function findByUser($user)
	{
		$qb = $this->createQueryBuilder('t');
		$qb
			->join('t.user', 'user')
			->where($qb->expr()->eq('user.id', ':userid'))
			->setParameter(':userid', $user);

		try { } catch (\Throwable $th) { }
		$query = $qb->getQuery();
		return $query->getResult();
	}
	public function getThisMonthsTasks($user, $month)
	{

		$conn = $this->getEntityManager()
            ->getConnection();

		$sql = " 
		select * from day_tasks where user_id = ? and month(date) = ?
    ";
        $stmt = $conn->prepare($sql);

		$stmt->bindValue(1, $user);
		$stmt->bindValue(2, $month);

		$stmt->execute();

		return $stmt->fetchAll();
	}
}
