<?php

namespace AppBundle\Repository;

/**
 * DayUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayUnitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastHourId($user, $month, $year)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        try{

            $qb->select('max(t.hourId) as hourId')
                ->from('AppBundle:DayUnit','t')
				->where($qb->expr()->eq('t.yearAt', ':year'))
				->andWhere($qb->expr()->eq('t.monthAt', ':month'))
				->andWhere($qb->expr()->eq('t.user', ':user'))
				->orderBy('t.hourId')
				->setParameter(':year', $year)
				->setParameter(':month', $month)
				->setParameter(':user', $user);

			return $qb->getQuery()->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {

			return 0;
		}

    }
}
