<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsByUser($user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('t');

        try{
            $qb->select('e')
            ->from('AppBundle:Event','e')
            ->where($qb->expr()->eq('e.user',':user'))
            ->setParameter(':user' ,$user);

            return $qb->getQuery()->getResult();

        }catch(\Doctrine\ORM\NoResultException $e)
        {
            return null;

        }
    }

	public function getThisMonthsEvents($user, $month, $year)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try {
			$qb->select('t')
				->from('AppBundle:Event', 't')
				->where($qb->expr()->eq('YEAR(t.starts)', ':year'))
				->andWhere($qb->expr()->eq('MONTH(t.starts)', ':month'))
				->andWhere($qb->expr()->eq('t.user', ':user'))
				->setParameter(':year', $year)
				->setParameter(':month', $month)
				->setParameter(':user', $user);

			return $qb->getQuery()->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {

			return null;
		}
	}
}
