<?php

namespace AppBundle\Repository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends \Doctrine\ORM\EntityRepository
{
	public function findGoalByUserAndMonth($month,$year,$user)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try{
			$qb->select('t')
			->from('AppBundle:Goal','t')
			->where($qb->expr()->eq('YEAR(t.date)',':year'))
			->andWhere($qb->expr()->eq('MONTH(t.date)',':month'))
			->andWhere($qb->expr()->eq('t.user',':user'))
			->setParameter(':year',$year)
			->setParameter(':month',$month)
			->setParameter(':user',$user);

			return $qb->getQuery()->getResult();
			}catch(\Doctrine\ORM\NoResultException $e){

					return null;
		}	

	}
}
