<?php

namespace AppBundle\Repository;

/**
 * MonthTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthTaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function getThisMonthsTasks($user, $month, $year)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try {
			$qb->select('t')
				->from('AppBundle:MonthTask', 't')
				->where($qb->expr()->eq('YEAR(t.date)', ':year'))
				->andWhere($qb->expr()->eq('MONTH(t.date)', ':month'))
				->andWhere($qb->expr()->eq('t.user', ':user'))
				->orderBy('t.date')
				->setParameter(':year', $year)
				->setParameter(':month', $month)
				->setParameter(':user', $user);

			return $qb->getQuery()->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {

			return null;
		}
	}
}
