<?php

namespace AppBundle\Repository;

/**
 * MonthTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
