<?php

namespace AppBundle\Repository;

/**
 * subgoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubgoalRepository extends \Doctrine\ORM\EntityRepository
{
}
