<?php

namespace AppBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findTranByUserAndMonth($month,$year,$user)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try{
			$qb->select('t')
			->from('AppBundle:Transaction','t')
			->where($qb->expr()->eq('YEAR(t.dateAt)',':year'))
			->andWhere($qb->expr()->eq('MONTH(t.dateAt)',':month'))
			->andWhere($qb->expr()->eq('t.user',':user'))
			->setParameter(':year',$year)
			->setParameter(':month',$month)
			->setParameter(':user',$user);

			return $qb->getQuery()->getResult();
			}catch(\Doctrine\ORM\NoResultException $e){

					return null;
		}	

	}

	public function findTotalPositiveAmount($month,$year,$user)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try{
			$qb->select('SUM(t.amount)')
			->from('AppBundle:Transaction','t')
			->where($qb->expr()->eq('YEAR(t.dateAt)',':year'))
			->andWhere('t.amount > 0')
			->andWhere($qb->expr()->eq('MONTH(t.dateAt)',':month'))
			->andWhere($qb->expr()->eq('t.user',':user'))
			->setParameter(':year',$year)
			->setParameter(':month',$month)
			->setParameter(':user',$user);

			return $qb->getQuery()->getResult();
			}catch(\Doctrine\ORM\NoResultException $e){

					return null;
		}	
	}

	public function findTotalNegativeAmount($month,$year,$user)
	{
		$qb = $this->getEntityManager()->createQueryBuilder('t');

		try{
			$qb->select('SUM(t.amount)')
			->from('AppBundle:Transaction','t')
			->where($qb->expr()->eq('YEAR(t.dateAt)',':year'))
			->andWhere('t.amount < 0')
			->andWhere($qb->expr()->eq('MONTH(t.dateAt)',':month'))
			->andWhere($qb->expr()->eq('t.user',':user'))
			->setParameter(':year',$year)
			->setParameter(':month',$month)
			->setParameter(':user',$user);

			return $qb->getQuery()->getResult();
			}catch(\Doctrine\ORM\NoResultException $e){

					return null;
		}	
	}
}
